### PR TITLE
Fix startup issues and WebSocket forwarding

### LINKED ISSUE #73: Unable to find concurrently
**Describe the bug**
When starting the CLI, it can't find concurrently.

**To Reproduce**
1. Start react app `cd frontend && npm start`
2. `swa start http://localhost:3000`

**Expected behavior**
CLI should start.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

### LINKED ISSUE #74: Cannot start app without API if there's a folder named api
**Describe the bug**
When starting the CLI, if the current directory has a folder named `api`, it is assumed that it's a function app and the CLI attempts to start it.

**To Reproduce**
1. Create a folder named `api`.
2. `swa start http://localhost:3000`

**Expected behavior**
CLI should start without an API.

**Actual behavior**
CLI attempts to start Azure Functions Core Tools in the `api` folder.

**Desktop (please complete the following information):**
 - OS: macOS

### LINKED ISSUE #75: Port forwarding is incorrect if passing URI for app or api
**Describe the bug**
If passing a URI of a running dev server or Functions Core Tools, the incorrect ports are used.

**To Reproduce**
1. Start a react app
2. `swa start http://localhost:3000`
3. Open `http://localhost:4200`

**Expected behavior**
App works in browser

**Actual behavior**
CLI tries to forward to port 4200 instead of 3000

image

**Desktop (please complete the following information):**
 - OS: macOS

### LINKED ISSUE #76: WebSocket forwarding to dev server crashes proxy
**Describe the bug**
App dev server has hot reloading via WebSockets is not working.

**To Reproduce**
1. Start a React dev server
2. `swa start http://localhost:3000/`

**Expected behavior**
Hot reloading should work.

**Actual behavior**
image

proxy.js crashes

Some investigation finds that this is caused by an error triggered by a `ws://` request, which executes the error handler that appears to be misconfigured. https://github.com/Azure/static-web-apps-cli/blob/3eb95382240ef60e1f71a21c3b81a43700ad5610/src/proxy.ts#L202-L209

**Desktop (please complete the following information):**
 - OS: macOS

### PR DESCRIPTION
**Pull request by anthonychu**
* Fix `concurrently` resolving to the wrong path (fixes #73)
* Don't default api folder to `api` (fixes #74)
* Use the correct port when running CLI with app or api URIs (fixes #75)
* Fix WebSocket forwarding to dev server (fixes #76)

### CODE REVIEW

File: src/proxy.ts [hunk 1]
```diff
@@ -198,25 +198,21 @@ const server = http.createServer(function (req, res) {
       target,
       secure: false,
     });
-
```
Comment (anthonychu) [inline src/proxy.ts:201]: This appears to be registering the `error` handler multiple times.

File: src/proxy.ts [hunk 2]
```diff
@@ -198,25 +198,21 @@ const server = http.createServer(function (req, res) {
...
-    proxyApp.on("error", function (err) {
-      console.log("app>>", req.method, target + req.url);
-      res.writeHead(500, {
```
Comment (anthonychu) [inline src/proxy.ts:204]: This is crashing the proxy because we're writing to the response after it's been closed.

File: src/proxy.ts [hunk 3]
```diff
@@ -198,25 +198,21 @@ const server = http.createServer(function (req, res) {
...
-        "Content-Type": "text/plain",
-      });
-
-      res.end(err.toString());
-    });
   }
 });
 
+proxyApp.on("error", function (err) {
```
Comment (anthonychu) [inline src/proxy.ts:204]: Moving this here so the handler is created once and print error to stderr.

This handler was called because the WebSocket target was misconfigured (see below).

File: src/proxy.ts [hunk 4]
```diff
@@ -198,25 +198,21 @@ const server = http.createServer(function (req, res) {
...
+
 const port = SWA_CLI_PORT;
 const host = SWA_CLI_HOST;
 const address = `http://${host}:${port}`;
 console.log(`SWA listening on ${address}`);
 server.on("upgrade", function (req, socket, head) {
+  console.log("app>", "Upgrading WebSocket");
   proxyApp.ws(req, socket, head, {
-    target: process.env.SWA_CLI_APP_URI,
+    target: SWA_CLI_APP_URI,
```
Comment (anthonychu) [inline src/proxy.ts:215]: Use the correct variable because `process.env.SWA_CLI_APP_URI` is not defined.

**Review by manekinekko — APPROVED** [review]
