### PR TITLE
fix: Print CLI version when running --verbose=silly

### LINKED ISSUE #231: Print CLI version when running --verbose=silly
Add CLI version when enabling `--verbose=silly`.

### PR DESCRIPTION
**Pull request by sgollapudi77**
Fixes #231

### CODE REVIEW

File: src/cli/commands/start.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export async function start(startContext: string, options: SWACLIConfig) {
 
   // get the app and api artifact locations
   let [appLocation, outputLocation, apiLocation] = [options.appLocation as string, options.outputLocation as string, options.apiLocation as string];
-
+  let packageInfo = require("../../../package.json");
```
Comment (manekinekko) [inline src/cli/commands/start.ts:53]: this should be placed at the head of the file, in the import section.

**Review by manekinekko — CHANGES_REQUESTED** [review]

**Comment by sgollapudi77** [comment]
Screenshot (11)

**Review by manekinekko — APPROVED** [review]
